spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: talex-server
  # datasource:
  #   driver-class-name: org.postgresql.Driver
  #   username: ${DB_USERNAME:postgres}
  #   password: ${DB_PASSWORD:12345}
  #   url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:talex-db}

  datasource:
    driver-class-name: org.postgresql.Driver
    username: neondb_owner
    password: npg_zEU3djeluHX7
    url: jdbc:postgresql://ep-long-silence-ao009tbp.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  data:
    redis:
      host: ${REDIS_HOST:station-empowering-kiss-54115.db.redis.io}
      port: ${REDIS_PORT:15883}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}
      timeout: 5000ms
  threads:
    virtual:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

integration:
  clients:
    fpt-ai:
      base-url: https://api.fpt.ai
      api-key: JKqZ83MbT68ELOzCZLEDVw9MdCIyUkPI
      connection-timeout-ms: 5000
      read-timeout-ms: 30000

terms:
  version: v1

eKYC:
  id-recognition:
    provider: fpt-ai

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10             # Xét 10 request gần nhất
        minimumNumberOfCalls: 5           # Cần tối thiểu 5 request để bắt đầu tính toán tỷ lệ lỗi
        failureRateThreshold: 50          # Nếu 50% số request bị lỗi hoặc timeout (>15s), mạch sẽ NGẮT (Open)
        slowCallRateThreshold: 50         # Nếu 50% số request chạy chậm hơn thời gian quy định
        slowCallDurationThreshold: 10000ms # Định nghĩa request chậm là > 10 giây
        waitDurationInOpenState: 30000ms  # Sau khi ngắt mạch, bắt buộc chờ 30 giây mới cho phép thử lại (Half-Open)
        permittedNumberOfCallsInHalfOpenState: 3 # Cho phép 3 request đi thử nghiệm khi mạch đang Half-Open
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      fptAiFrontOcr:
        baseConfig: default
      fptAiBackOcr:
        baseConfig: default

jwt:
  secret: ${JWT_SECRET:dGFsZXgtc2VjcmV0LWtleS1mb3ItZGV2ZWxvcG1lbnQtb25seQ==}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

google:
  client-id:
    web: ${GOOGLE_CLIENT_ID_WEB:}
    android: ${GOOGLE_CLIENT_ID_ANDROID:}
    ios: ${GOOGLE_CLIENT_ID_IOS:}

otp:
  expiration-minutes: 10
  length: 6
